name: 'Push on Dev environment'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'main.tf'
  workflow_dispatch:
    inputs:
      actions:
        description: 'terraform action (apply or destroy)'
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy
  workflow_run:
    workflows: ['Deploy Lambda Functions'] # Name of the deploy.yml workflow
    branches: [main]
    types:
      - completed
env:
  TF_LOG: INFO
  TF_INPUT: false

permissions:
    id-token: write
    contents: read

jobs:
  terraform:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event.workflow_run.conclusion == 'success')
    name: 'Terraform deploy'
    runs-on: ubuntu-latest

    # Use the Bash shell
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    env:
      TF_VAR_region: eu-west-2
      TF_VAR_projectName: "revolution"
      TF_VAR_environment: "staging"

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.2"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # Updated to latest stable version
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # Replace with your IAM role ARN
        aws-region: ${{ vars.AWS_REGION }}
        role-session-name: GitHubActionsSession

    # Initialize Terraform
    - name: Terraform Init
      id: init
      run: terraform init

    #terraform plan
    - name: Terraform plan
      id: plan
      run: |
        if [ "${{ github.event.inputs.actions || 'apply' }}" == "destroy" ]; then
            terraform plan -destroy -out=tfplan -no-color > plan-output.txt
        else
            terraform plan -out=tfplan -no-color > plan-output.txt
        fi
      continue-on-error: false

    #terraform apply or destroy
    - name: Terraform Apply or Destroy
      #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
      id: tfAppDest
      run: |
        if [ "${{ github.event.inputs.actions || 'apply' }}" == 'apply' ]; then
            terraform apply --auto-approve tfplan
        else
            terraform destroy --auto-approve
        fi

    # # Run Terraform apply if branch is main
    # - name: Terraform Apply for Main branch
    #   if: github.ref == 'refs/heads/main'
    #   id: apply
    #   run: terraform apply -auto-approve
